### ISSUE TITLE
Cannot use it with imports @kinde-oss/kinde-node-express

### ISSUE THREAD

**Issue by whitetown** [kinde-oss/kinde-node-express#29] opened 2024-05-23 11:47 UTC
### Prerequisites

- [X] I have searched the repository’s issues and [Kinde community](https://thekindecommunity.slack.com/archives/C04K316BXEH) to ensure my issue isn’t a duplicate
- [X] I have checked the latest version of the library to replicate my issue
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### Describe the issue

import { setupKinde } from '@kinde-oss/kinde-node-express'
or 
import pkg from '@kinde-oss/kinde-node-express'

(node:27836) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
warning:65
Uncaught SyntaxError .../node_modules/@kinde-oss/kinde-node-express/dist/index.js:1
import { getInternalClient, setupInternalClient } from './setup';

the entire backend is written with 'import', there is no way for me to change it to 'require'

### Library URL

https://github.com/kinde-oss/kinde-node-express

### Library version

latest

### Operating system(s)

macOS

### Operating system version(s)

latest

**Comment by dg-robinson** [comment] 2024-05-29 11:53
@whitetown try using v1.0.12. I'm experiencing a similar issue, and that was the last version that worked correctly with ESM imports.

**Comment by DanielRivers** [comment] 2024-05-29 15:00
I have a new build locally and will get this out in the next hour of so

**Comment by whitetown** [comment] 2024-05-29 16:05
I already chose clerk and wish all the same)

**Comment by DanielRivers** [comment] 2024-05-29 16:10
@whitetown Sorry to hear that, version 1.5 has now been released with this resolved.

@dg-robinson new version release which resolves imports

**Comment by rip32700** [comment] 2024-05-30 21:01
facing the same issue with 1.5.0 @DanielRivers

**Comment by DanielRivers** [comment] 2024-05-30 21:02
@rip32700 Can you explain what issue you're seeing?  If possible share code example.  I have this all working locally with imports.

**Comment by dg-robinson** [comment] 2024-06-03 10:36
@DanielRivers I've upgraded to 1.5.0 and I'm now seeing a different issue: `TypeError: Cannot destructure property 'audience' of 't' as it is undefined.
    at Rq (file:///.../node_modules/@kinde-oss/kinde-node-express/dist/index.esm.js:313:109874)`. It seems to be mixing the contents of the map with the regular output and breaking everything. 

Here's the [latest verion](https://github.com/user-attachments/files/15532567/1.5.0.txt) versus the [last working version](https://github.com/user-attachments/files/15532568/1.0.12.txt), at least for me. 1.4.1 didn't have this problem, so maybe an issue with the Rollup implementation? 

Do you think there could be some issue with local Node or npm versions, perhaps? I'm running Node v21.5.0 and npm 10.5.2 if that helps at all.

**Comment by DanielRivers** [comment] 2024-06-03 11:01
Hi @dg-robinson,

I have just released a new beta version which I have tested on both ESM and CJS.  Could you please try `1.6.0-0` and let me know.

**Comment by DanielRivers** [comment] 2024-06-03 22:45
Fixed in 1.6.0

**Closed by DanielRivers** 2024-06-03 22:45 UTC
Labels: bug

**Comment by dg-robinson** [comment] 2024-06-25 21:24
Sorry for the delay in responding @DanielRivers. I've just tried 1.6.0, but I'm getting exactly the same as behaviour as 1.5.0. Is there any information I can give you that might be useful?

**Comment by DanielRivers** [comment] 2024-06-25 22:01
@dg-robinson could you supply me with a minimal reproduction repo? I'm not able to reproduce locally.

**Comment by dg-robinson** [comment] 2024-09-10 11:52
@DanielRivers sorry it's taken so long! I finally got around to making a minimal reproduction for you: https://github.com/dg-robinson/kinde
